/**
 * customer-portal.service.ts
 *
 * Magic-link authentication + customer self-service data access.
 *
 * Auth flow:
 *   1. Admin calls sendMagicLink(tenantId, email)
 *   2. A CustomerPortalSession is created with a unique token (cuid)
 *      and a 24-hour expiry.
 *   3. An email is sent containing the portal link.
 *   4. Customer visits the link; the token is validated via
 *      validatePortalToken(), which returns customerId + tenantId.
 *   5. All subsequent data-access calls are scoped to that
 *      (customerId, tenantId) pair — no JWT required.
 *
 * Security notes:
 *   - Token stored in DB (not in JWT) so it can be revoked instantly.
 *   - All customer-data queries include BOTH customerId AND tenantId
 *     to prevent cross-tenant data access.
 *   - Only SENT, OVERDUE, and PAID invoices are exposed to the portal
 *     (DRAFT and CANCELLED remain internal).
 *   - Quote operations are guarded: only SENT quotes can be
 *     accepted/rejected; ownership by (quoteId + customerId + tenantId).
 */

import { prisma }     from '../../config/database';
import { sendEmail }  from '../../services/email.service';
import { logger }     from '../../config/logger';
import {
  generateInvoicePDF,
  InvoiceForPDF,
  TenantForPDF,
  CustomerForPDF,
} from '../invoices/invoice.pdf.service';

// ─── Environment helpers ───────────────────────────────────────────────────────

function frontendUrl(): string {
  return (process.env.FRONTEND_URL ?? 'https://app.erp.local').replace(/\/$/, '');
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PortalSummary {
  openInvoices:    number;
  totalOwed:       number;
  overdueInvoices: number;
  overdueAmount:   number;
  lastPaymentDate: string | null;
  activeQuotes:    number;
}

export interface ValidateTokenResult {
  valid:      boolean;
  customerId?: string;
  tenantId?:   string;
  sessionId?:  string;
}

// ─── sendMagicLink ────────────────────────────────────────────────────────────

/**
 * ADMIN-initiated: send a magic-link email to a customer.
 * Looks up the customer by email within the tenant, creates a session,
 * and dispatches the email.
 */
export async function sendMagicLink(
  tenantId: string,
  email:    string
): Promise<{ sent: boolean; message: string }> {
  // 1. Resolve the customer — email is not guaranteed unique globally,
  //    so we scope to tenantId.
  const customer = await prisma.customer.findFirst({
    where: { tenantId, email },
    select: { id: true, name: true, email: true },
  });

  if (!customer) {
    return { sent: false, message: 'Customer not found' };
  }

  // 2. Revoke any prior active sessions for this customer (optional clean-up).
  //    Keeps only one active magic-link per customer at a time.
  await prisma.customerPortalSession.updateMany({
    where: { tenantId, customerId: customer.id, isRevoked: false },
    data:  { isRevoked: true },
  });

  // 3. Create new session (token auto-generated by @default(cuid()) in schema).
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1_000); // +24 h

  const session = await prisma.customerPortalSession.create({
    data: {
      tenantId,
      customerId: customer.id,
      email,
      expiresAt,
    },
    select: { token: true },
  });

  // 4. Build magic-link URL.
  const link = `${frontendUrl()}/portal/${tenantId}?token=${session.token}`;

  // 5. Send email.
  const html = `
    <!DOCTYPE html>
    <html lang="he" dir="rtl">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <body style="font-family: Arial, sans-serif; background: #f9fafb; margin: 0; padding: 0;">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:40px auto; background:#fff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,.08);">
        <tr>
          <td style="background:#1a56db; padding:28px 40px; border-radius:8px 8px 0 0;">
            <h1 style="color:#fff; margin:0; font-size:22px;">פורטל לקוחות</h1>
          </td>
        </tr>
        <tr>
          <td style="padding:36px 40px;">
            <p style="font-size:16px; color:#374151; margin:0 0 16px 0;">שלום ${customer.name},</p>
            <p style="font-size:15px; color:#4b5563; margin:0 0 28px 0;">
              לחצו על הכפתור למטה לכניסה לפורטל הלקוחות שלכם.
              הקישור בתוקף ל-24 שעות.
            </p>
            <a href="${link}"
               style="display:inline-block; background:#1a56db; color:#fff; text-decoration:none;
                      padding:14px 32px; border-radius:6px; font-size:16px; font-weight:600;">
              כניסה לפורטל
            </a>
            <p style="font-size:13px; color:#9ca3af; margin:28px 0 0 0;">
              אם לא ביקשתם קישור זה, ניתן להתעלם ממייל זה בבטחה.
            </p>
            <hr style="border:none; border-top:1px solid #e5e7eb; margin:28px 0;" />
            <p style="font-size:12px; color:#d1d5db; margin:0;">
              לינק ישיר: <a href="${link}" style="color:#6b7280;">${link}</a>
            </p>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;

  await sendEmail({
    to:      email,
    subject: 'כניסה לפורטל לקוחות',
    html,
  });

  logger.info('sendMagicLink: magic link sent', {
    tenantId,
    customerId: customer.id,
    email,
  });

  return { sent: true, message: 'Magic link sent' };
}

// ─── validatePortalToken ──────────────────────────────────────────────────────

/**
 * Validates a portal token.
 * Returns { valid: true, customerId, tenantId, sessionId } on success,
 * or { valid: false } when the token is missing, revoked, or expired.
 *
 * Side effect: updates lastUsedAt on the session.
 */
export async function validatePortalToken(token: string): Promise<ValidateTokenResult> {
  const session = await prisma.customerPortalSession.findUnique({
    where: { token },
    select: {
      id:         true,
      tenantId:   true,
      customerId: true,
      expiresAt:  true,
      isRevoked:  true,
    },
  });

  if (!session)           return { valid: false };
  if (session.isRevoked)  return { valid: false };
  if (session.expiresAt < new Date()) return { valid: false };

  // Touch lastUsedAt (fire-and-forget — don't delay the request).
  prisma.customerPortalSession
    .update({ where: { token }, data: { lastUsedAt: new Date() } })
    .catch((err: unknown) => logger.warn('validatePortalToken: could not update lastUsedAt', { err }));

  return {
    valid:      true,
    customerId: session.customerId,
    tenantId:   session.tenantId,
    sessionId:  session.id,
  };
}

// ─── revokeSession ────────────────────────────────────────────────────────────

/**
 * ADMIN-initiated: immediately revoke a portal session.
 * Scoped to tenantId to prevent cross-tenant revocation.
 */
export async function revokeSession(
  sessionId: string,
  tenantId:  string
): Promise<void> {
  const session = await prisma.customerPortalSession.findFirst({
    where: { id: sessionId, tenantId },
    select: { id: true },
  });

  if (!session) {
    const err: any = new Error('Session not found');
    err.statusCode = 404;
    throw err;
  }

  await prisma.customerPortalSession.update({
    where: { id: sessionId },
    data:  { isRevoked: true },
  });
}

// ─── listActiveSessions ───────────────────────────────────────────────────────

/**
 * ADMIN: list all non-revoked, non-expired sessions for this tenant.
 */
export async function listActiveSessions(tenantId: string) {
  return prisma.customerPortalSession.findMany({
    where: {
      tenantId,
      isRevoked: false,
      expiresAt: { gt: new Date() },
    },
    select: {
      id:         true,
      email:      true,
      customerId: true,
      customer:   { select: { name: true } },
      createdAt:  true,
      expiresAt:  true,
      lastUsedAt: true,
    },
    orderBy: { createdAt: 'desc' },
  });
}

// ─── getPortalCustomer ────────────────────────────────────────────────────────

/**
 * Returns the customer's public profile.
 * Exposes only name, email, phone, address — no internal IDs beyond customerId.
 */
export async function getPortalCustomer(customerId: string, tenantId: string) {
  const customer = await prisma.customer.findFirst({
    where: { id: customerId, tenantId },
    select: {
      id:      true,
      name:    true,
      email:   true,
      phone:   true,
      address: true,
      type:    true,
    },
  });

  if (!customer) {
    const err: any = new Error('Customer not found');
    err.statusCode = 404;
    throw err;
  }

  return customer;
}

// ─── getPortalInvoices ────────────────────────────────────────────────────────

/**
 * Paginated list of invoices visible to the portal customer.
 * Only SENT, OVERDUE, and PAID statuses are shown.
 */
export async function getPortalInvoices(
  customerId: string,
  tenantId:   string,
  filters?: {
    status?: 'SENT' | 'OVERDUE' | 'PAID';
    page?:   number;
    limit?:  number;
  }
) {
  const page  = Math.max(1, filters?.page  ?? 1);
  const limit = Math.min(100, Math.max(1, filters?.limit ?? 20));
  const skip  = (page - 1) * limit;

  // Only these three statuses are visible to the customer.
  const allowedStatuses = ['SENT', 'OVERDUE', 'PAID'] as const;
  const statusFilter = filters?.status && allowedStatuses.includes(filters.status)
    ? [filters.status]
    : allowedStatuses;

  const where = {
    tenantId,
    customerId,
    status:    { in: statusFilter as any },
    deletedAt: null,
  };

  const [items, total] = await Promise.all([
    prisma.invoice.findMany({
      where,
      skip,
      take: limit,
      orderBy: { date: 'desc' },
      select: {
        id:          true,
        number:      true,
        invoiceType: true,
        date:        true,
        dueDate:     true,
        status:      true,
        subtotal:    true,
        vatAmount:   true,
        total:       true,
        currency:    true,
        notes:       true,
        paidAt:      true,
      },
    }),
    prisma.invoice.count({ where }),
  ]);

  return {
    items: items.map(inv => ({
      ...inv,
      subtotal:  Number(inv.subtotal),
      vatAmount: Number(inv.vatAmount),
      total:     Number(inv.total),
    })),
    total,
    page,
    limit,
    pages: Math.ceil(total / limit),
  };
}

// ─── getPortalInvoicePDF ──────────────────────────────────────────────────────

/**
 * Generates and returns a PDF Buffer for the given invoice.
 * Verifies the invoice belongs to the authenticated portal customer.
 */
export async function getPortalInvoicePDF(
  invoiceId:  string,
  customerId: string,
  tenantId:   string
): Promise<Buffer> {
  // Fetch invoice with ownership check.
  const invoice = await prisma.invoice.findFirst({
    where: {
      id:         invoiceId,
      customerId,
      tenantId,
      status:     { in: ['SENT', 'OVERDUE', 'PAID'] },
      deletedAt:  null,
    },
    include: {
      lines:    true,
      customer: { select: { name: true, email: true, phone: true, businessId: true, address: true } },
      tenant:   { select: { name: true, vatNumber: true, businessNumber: true, address: true, phone: true, email: true } },
    },
  });

  if (!invoice) {
    const err: any = new Error('Invoice not found');
    err.statusCode = 404;
    throw err;
  }

  const invoiceForPDF: InvoiceForPDF = {
    id:             invoice.id,
    number:         invoice.number,
    invoiceType:    invoice.invoiceType,
    date:           invoice.date,
    dueDate:        invoice.dueDate,
    status:         invoice.status,
    subtotal:       Number(invoice.subtotal),
    vatAmount:      Number(invoice.vatAmount),
    total:          Number(invoice.total),
    discountAmount: invoice.discountAmount ? Number(invoice.discountAmount) : null,
    notes:          invoice.notes,
    lines:          invoice.lines.map(l => ({
      description: l.description,
      quantity:    Number(l.quantity),
      unitPrice:   Number(l.unitPrice),
      vatRate:     Number(l.vatRate),
      lineTotal:   Number(l.lineTotal),
    })),
  };

  const tenantForPDF: TenantForPDF = {
    name:           invoice.tenant.name,
    vatNumber:      invoice.tenant.vatNumber,
    businessNumber: invoice.tenant.businessNumber,
    address:        invoice.tenant.address,
    phone:          invoice.tenant.phone,
    email:          invoice.tenant.email,
  };

  const customerForPDF: CustomerForPDF = {
    name:       invoice.customer.name,
    email:      invoice.customer.email,
    phone:      invoice.customer.phone,
    businessId: invoice.customer.businessId,
    address:    invoice.customer.address,
  };

  return generateInvoicePDF(invoiceForPDF, tenantForPDF, customerForPDF);
}

// ─── getPortalQuotes ──────────────────────────────────────────────────────────

/**
 * Returns all SENT or ACCEPTED quotes for the portal customer.
 */
export async function getPortalQuotes(customerId: string, tenantId: string) {
  const quotes = await prisma.quote.findMany({
    where: {
      tenantId,
      customerId,
      status: { in: ['SENT', 'ACCEPTED'] },
    },
    select: {
      id:         true,
      number:     true,
      title:      true,
      status:     true,
      issueDate:  true,
      expiryDate: true,
      subtotal:   true,
      vatAmount:  true,
      total:      true,
      notes:      true,
      termsConditions: true,
      lines: {
        select: {
          id:          true,
          description: true,
          quantity:    true,
          unitPrice:   true,
          discount:    true,
          lineTotal:   true,
          sortOrder:   true,
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
    orderBy: { issueDate: 'desc' },
  });

  return quotes.map(q => ({
    ...q,
    subtotal:  Number(q.subtotal),
    vatAmount: Number(q.vatAmount),
    total:     Number(q.total),
    lines: q.lines.map(l => ({
      ...l,
      quantity:  Number(l.quantity),
      unitPrice: Number(l.unitPrice),
      discount:  Number(l.discount),
      lineTotal: Number(l.lineTotal),
    })),
  }));
}

// ─── getPortalPayments ────────────────────────────────────────────────────────

/**
 * Returns all payment records for invoices belonging to the portal customer.
 * Joins through the Invoice table to ensure ownership.
 */
export async function getPortalPayments(customerId: string, tenantId: string) {
  const payments = await prisma.invoicePayment.findMany({
    where: {
      tenantId,
      invoice: { customerId },
    },
    select: {
      id:        true,
      amount:    true,
      method:    true,
      date:      true,
      reference: true,
      notes:     true,
      createdAt: true,
      invoice:   { select: { id: true, number: true, total: true } },
    },
    orderBy: { date: 'desc' },
  });

  return payments.map(p => ({
    ...p,
    amount: Number(p.amount),
    invoice: { ...p.invoice, total: Number(p.invoice.total) },
  }));
}

// ─── acceptPortalQuote ────────────────────────────────────────────────────────

/**
 * Customer accepts a SENT quote.
 * Validates ownership by (quoteId + customerId + tenantId).
 */
export async function acceptPortalQuote(
  quoteId:    string,
  customerId: string,
  tenantId:   string
) {
  const quote = await prisma.quote.findFirst({
    where: { id: quoteId, customerId, tenantId },
    select: { id: true, status: true },
  });

  if (!quote) {
    const err: any = new Error('Quote not found');
    err.statusCode = 404;
    throw err;
  }

  if (quote.status !== 'SENT') {
    const err: any = new Error(`Cannot accept a quote with status ${quote.status}`);
    err.statusCode = 400;
    throw err;
  }

  return prisma.quote.update({
    where: { id: quoteId },
    data:  { status: 'ACCEPTED' },
    select: {
      id:     true,
      number: true,
      status: true,
      title:  true,
      total:  true,
    },
  });
}

// ─── rejectPortalQuote ────────────────────────────────────────────────────────

/**
 * Customer rejects a SENT quote.
 * Validates ownership by (quoteId + customerId + tenantId).
 */
export async function rejectPortalQuote(
  quoteId:    string,
  customerId: string,
  tenantId:   string
) {
  const quote = await prisma.quote.findFirst({
    where: { id: quoteId, customerId, tenantId },
    select: { id: true, status: true },
  });

  if (!quote) {
    const err: any = new Error('Quote not found');
    err.statusCode = 404;
    throw err;
  }

  if (quote.status !== 'SENT') {
    const err: any = new Error(`Cannot reject a quote with status ${quote.status}`);
    err.statusCode = 400;
    throw err;
  }

  return prisma.quote.update({
    where: { id: quoteId },
    data:  { status: 'REJECTED' },
    select: {
      id:     true,
      number: true,
      status: true,
      title:  true,
      total:  true,
    },
  });
}

// ─── getPortalSummary ─────────────────────────────────────────────────────────

/**
 * Dashboard summary for the portal customer.
 * All figures are derived from SENT/OVERDUE/PAID invoices and SENT/ACCEPTED quotes.
 */
export async function getPortalSummary(
  customerId: string,
  tenantId:   string
): Promise<PortalSummary> {
  const now = new Date();

  // Aggregate open (SENT + OVERDUE) and overdue invoices in one query.
  const [openAgg, overdueAgg] = await Promise.all([
    prisma.invoice.aggregate({
      where: {
        tenantId,
        customerId,
        status:    { in: ['SENT', 'OVERDUE'] },
        deletedAt: null,
      },
      _count: { id: true },
      _sum:   { total: true },
    }),
    prisma.invoice.aggregate({
      where: {
        tenantId,
        customerId,
        status:    'OVERDUE',
        deletedAt: null,
      },
      _count: { id: true },
      _sum:   { total: true },
    }),
  ]);

  // Most recent payment date for this customer's invoices.
  const lastPayment = await prisma.invoicePayment.findFirst({
    where: {
      tenantId,
      invoice: { customerId },
    },
    orderBy: { date: 'desc' },
    select:  { date: true },
  });

  // Active (SENT) quotes only — ACCEPTED ones are already committed.
  const activeQuotesCount = await prisma.quote.count({
    where: { tenantId, customerId, status: 'SENT' },
  });

  return {
    openInvoices:    openAgg._count.id,
    totalOwed:       Number(openAgg._sum.total ?? 0),
    overdueInvoices: overdueAgg._count.id,
    overdueAmount:   Number(overdueAgg._sum.total ?? 0),
    lastPaymentDate: lastPayment ? lastPayment.date.toISOString() : null,
    activeQuotes:    activeQuotesCount,
  };
}
