/**
 * Payment Links Service
 *
 * Manages creation, retrieval, status updates, and email delivery of
 * payment links tied to invoices. Public-facing token-based endpoints
 * allow payers to view and confirm payment without authentication.
 */

import { PaymentLinkStatus } from '@prisma/client';
import { prisma } from '../../config/database';
import { sendEmail } from '../../services/email.service';
import { logger } from '../../config/logger';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const FRONTEND_URL = process.env.FRONTEND_URL ?? 'https://app.example.com';

function buildPublicUrl(token: string): string {
  return `${FRONTEND_URL}/pay/${token}`;
}

function formatILS(amount: number): string {
  return new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS' }).format(amount);
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('he-IL', { year: 'numeric', month: '2-digit', day: '2-digit' });
}

// ---------------------------------------------------------------------------
// createPaymentLink
// ---------------------------------------------------------------------------

export interface CreatePaymentLinkInput {
  expiresInDays?: number;
  notes?: string;
}

export async function createPaymentLink(
  tenantId: string,
  invoiceId: string,
  data: CreatePaymentLinkInput
) {
  // Verify invoice belongs to tenant and check status
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
  });

  if (!invoice || invoice.tenantId !== tenantId) {
    throw new Error('Invoice not found');
  }

  if (invoice.status !== 'SENT' && invoice.status !== 'OVERDUE') {
    throw new Error(
      `Cannot create a payment link for invoice with status "${invoice.status}". Invoice must be SENT or OVERDUE.`
    );
  }

  const expiresInDays = data.expiresInDays ?? 30;
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + expiresInDays);

  const link = await prisma.paymentLink.create({
    data: {
      tenantId,
      invoiceId,
      amount:    invoice.total,
      expiresAt,
      notes:     data.notes,
      // token is auto-generated by Prisma @default(cuid())
    },
  });

  return {
    ...link,
    amount:    Number(link.amount),
    publicUrl: buildPublicUrl(link.token),
  };
}

// ---------------------------------------------------------------------------
// listPaymentLinks
// ---------------------------------------------------------------------------

export interface ListPaymentLinksFilters {
  invoiceId?: string;
  status?:    PaymentLinkStatus;
  page?:      number;
  limit?:     number;
}

export async function listPaymentLinks(
  tenantId: string,
  filters: ListPaymentLinksFilters = {}
) {
  const { invoiceId, status, page = 1, limit = 25 } = filters;
  const skip = (page - 1) * limit;

  const where = {
    tenantId,
    ...(invoiceId ? { invoiceId } : {}),
    ...(status    ? { status }    : {}),
  };

  const [items, total] = await Promise.all([
    prisma.paymentLink.findMany({
      where,
      include: {
        invoice: {
          select: {
            number:   true,
            status:   true,
            dueDate:  true,
            customer: { select: { name: true, email: true } },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
      skip,
      take: limit,
    }),
    prisma.paymentLink.count({ where }),
  ]);

  return {
    items: items.map(link => ({
      ...link,
      amount:    Number(link.amount),
      publicUrl: buildPublicUrl(link.token),
    })),
    total,
    page,
    limit,
  };
}

// ---------------------------------------------------------------------------
// getPaymentLink
// ---------------------------------------------------------------------------

export async function getPaymentLink(id: string, tenantId: string) {
  const link = await prisma.paymentLink.findUnique({
    where: { id },
    include: {
      invoice: {
        select: {
          number:   true,
          status:   true,
          date:     true,
          dueDate:  true,
          total:    true,
          customer: { select: { name: true, email: true, phone: true } },
        },
      },
    },
  });

  if (!link || link.tenantId !== tenantId) {
    throw new Error('Payment link not found');
  }

  return {
    ...link,
    amount:    Number(link.amount),
    publicUrl: buildPublicUrl(link.token),
  };
}

// ---------------------------------------------------------------------------
// getPaymentLinkByToken  (PUBLIC — no tenantId required)
// ---------------------------------------------------------------------------

export async function getPaymentLinkByToken(token: string) {
  const link = await prisma.paymentLink.findUnique({
    where: { token },
    include: {
      invoice: {
        select: {
          number:   true,
          dueDate:  true,
          customer: { select: { name: true } },
        },
      },
    },
  });

  if (!link) {
    const err: any = new Error('Payment link not found');
    err.statusCode = 404;
    throw err;
  }

  // Auto-expire if past expiresAt and still ACTIVE
  if (link.status === 'ACTIVE' && link.expiresAt < new Date()) {
    await prisma.paymentLink.update({
      where: { id: link.id },
      data:  { status: 'EXPIRED' },
    });
    const err: any = new Error('תוקף לינק התשלום פג');
    err.statusCode = 410;
    throw err;
  }

  // Return only public-safe fields — no tenantId internals
  return {
    id:            link.id,
    token:         link.token,
    amount:        Number(link.amount),
    status:        link.status,
    expiresAt:     link.expiresAt,
    paidAt:        link.paidAt,
    notes:         link.notes,
    publicUrl:     buildPublicUrl(link.token),
    invoiceNumber: link.invoice.number,
    customerName:  link.invoice.customer.name,
    dueDate:       link.invoice.dueDate,
  };
}

// ---------------------------------------------------------------------------
// markAsPaid
// ---------------------------------------------------------------------------

export interface MarkAsPaidInput {
  payerName?:  string;
  payerEmail?: string;
}

export async function markAsPaid(
  id: string,
  tenantId: string,
  data: MarkAsPaidInput
) {
  const link = await prisma.paymentLink.findUnique({
    where: { id },
    include: {
      invoice: {
        select: { number: true, total: true, status: true },
      },
    },
  });

  if (!link || link.tenantId !== tenantId) {
    throw new Error('Payment link not found');
  }
  if (link.status === 'PAID') {
    throw new Error('Payment link is already marked as paid');
  }
  if (link.status === 'CANCELLED') {
    throw new Error('Cannot mark a cancelled payment link as paid');
  }
  if (link.status === 'EXPIRED') {
    throw new Error('Cannot mark an expired payment link as paid');
  }

  const now = new Date();

  return prisma.$transaction(async (tx) => {
    // 1. Mark the link as PAID
    const updatedLink = await tx.paymentLink.update({
      where: { id },
      data: {
        status:     'PAID',
        paidAt:     now,
        payerName:  data.payerName,
        payerEmail: data.payerEmail,
      },
    });

    // 2. Create an InvoicePayment record
    const payment = await tx.invoicePayment.create({
      data: {
        invoiceId: link.invoiceId,
        tenantId,
        amount:    link.amount,
        method:    'OTHER',          // PAYMENT_LINK maps to OTHER — no dedicated enum value
        date:      now,
        reference: `PAYMENT_LINK:${link.token}`,
        notes:     `תשלום באמצעות לינק — ${data.payerName ?? 'לא ידוע'}`,
        createdBy: tenantId,         // system-initiated; no user session available
      },
    });

    // 3. Check if invoice is now fully paid
    const agg = await tx.invoicePayment.aggregate({
      where: { invoiceId: link.invoiceId },
      _sum:  { amount: true },
    });

    const totalPaid     = Number(agg._sum.amount ?? 0);
    const invoiceTotal  = Number(link.invoice.total);
    const isFullyPaid   = totalPaid >= invoiceTotal;

    if (isFullyPaid) {
      await tx.invoice.update({
        where: { id: link.invoiceId },
        data:  { status: 'PAID', paidAt: now },
      });
    }

    return {
      ...updatedLink,
      amount:    Number(updatedLink.amount),
      publicUrl: buildPublicUrl(updatedLink.token),
      payment:   { ...payment, amount: Number(payment.amount) },
      invoiceFullyPaid: isFullyPaid,
    };
  });
}

// ---------------------------------------------------------------------------
// cancelPaymentLink
// ---------------------------------------------------------------------------

export async function cancelPaymentLink(id: string, tenantId: string) {
  const link = await prisma.paymentLink.findUnique({ where: { id } });

  if (!link || link.tenantId !== tenantId) {
    throw new Error('Payment link not found');
  }
  if (link.status === 'PAID') {
    throw new Error('Cannot cancel a paid payment link');
  }
  if (link.status === 'CANCELLED') {
    throw new Error('Payment link is already cancelled');
  }

  const updated = await prisma.paymentLink.update({
    where: { id },
    data:  { status: 'CANCELLED' },
  });

  return {
    ...updated,
    amount:    Number(updated.amount),
    publicUrl: buildPublicUrl(updated.token),
  };
}

// ---------------------------------------------------------------------------
// expireOverdueLinks
// ---------------------------------------------------------------------------

/**
 * Bulk-expire all ACTIVE payment links whose expiresAt is in the past.
 * Pass tenantId to scope to a single tenant, or omit for a global sweep.
 */
export async function expireOverdueLinks(tenantId?: string) {
  const result = await prisma.paymentLink.updateMany({
    where: {
      status:    'ACTIVE',
      expiresAt: { lt: new Date() },
      ...(tenantId ? { tenantId } : {}),
    },
    data: { status: 'EXPIRED' },
  });

  return result.count;
}

// ---------------------------------------------------------------------------
// sendPaymentLinkEmail
// ---------------------------------------------------------------------------

/**
 * Fetch the payment link with invoice + customer data, then send an email
 * containing the public URL, amount and expiry date.
 */
export async function sendPaymentLinkEmail(id: string, tenantId: string): Promise<void> {
  const link = await prisma.paymentLink.findUnique({
    where: { id },
    include: {
      invoice: {
        select: {
          number:   true,
          customer: { select: { name: true, email: true } },
        },
      },
    },
  });

  if (!link || link.tenantId !== tenantId) {
    throw new Error('Payment link not found');
  }

  const customerEmail = link.invoice.customer.email;
  if (!customerEmail) {
    throw new Error('אין כתובת דוא"ל ללקוח');
  }

  if (link.status !== 'ACTIVE') {
    throw new Error(`לא ניתן לשלוח לינק תשלום עם סטטוס "${link.status}"`);
  }

  const publicUrl     = buildPublicUrl(link.token);
  const formattedAmt  = formatILS(Number(link.amount));
  const formattedExp  = formatDate(link.expiresAt);
  const customerName  = link.invoice.customer.name;
  const invoiceNumber = link.invoice.number;

  const html = `<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
  <meta charset="UTF-8" />
  <title>לינק לתשלום</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f6f9;font-family:Arial,Helvetica,sans-serif;direction:rtl;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f4f6f9;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" border="0"
               style="background-color:#ffffff;border-radius:8px;overflow:hidden;
                      box-shadow:0 2px 8px rgba(0,0,0,0.08);max-width:600px;width:100%;">
          <tr>
            <td style="background-color:#1a56db;padding:24px 32px;">
              <p style="margin:0;font-size:22px;font-weight:bold;color:#ffffff;">מערכת חשבשבת</p>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <h1 style="margin:0 0 8px 0;font-size:24px;color:#1a202c;">לינק לתשלום חשבונית</h1>
              <p style="margin:0 0 24px 0;font-size:14px;color:#718096;">מספר חשבונית: <strong>${invoiceNumber}</strong></p>

              <p style="margin:0 0 16px 0;font-size:14px;color:#4a5568;">
                שלום <strong>${customerName}</strong>,<br />
                נשלח לך לינק לביצוע תשלום עבור החשבונית שפורטה מעלה.
              </p>

              <table width="100%" cellpadding="0" cellspacing="0" border="0"
                     style="background-color:#f7fafc;border-radius:6px;border:1px solid #e2e8f0;margin-bottom:24px;">
                <tr>
                  <td style="padding:20px 24px;">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td style="padding:6px 0;font-size:13px;color:#718096;">סכום לתשלום</td>
                        <td style="padding:6px 0;text-align:left;font-size:14px;font-weight:600;color:#2d3748;">${formattedAmt}</td>
                      </tr>
                      <tr>
                        <td style="padding:6px 0;border-top:1px solid #e2e8f0;font-size:13px;color:#718096;">תוקף הלינק</td>
                        <td style="padding:6px 0;border-top:1px solid #e2e8f0;text-align:left;font-size:14px;color:#2d3748;">${formattedExp}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <table cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px 0;">
                <tr>
                  <td style="border-radius:6px;background-color:#1a56db;">
                    <a href="${publicUrl}"
                       style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:bold;
                              color:#ffffff;text-decoration:none;border-radius:6px;">
                      לתשלום לחץ כאן
                    </a>
                  </td>
                </tr>
              </table>

              <p style="margin:0;font-size:12px;color:#718096;line-height:1.6;">
                לחלופין, העתק את הכתובת לדפדפן:<br />
                <a href="${publicUrl}" style="color:#1a56db;word-break:break-all;">${publicUrl}</a>
              </p>
            </td>
          </tr>
          <tr>
            <td style="background-color:#f0f4f8;padding:16px 32px;border-top:1px solid #e2e8f0;">
              <p style="margin:0;font-size:12px;color:#718096;text-align:center;">
                הודעה זו נשלחה אוטומטית ממערכת חשבשבת. אנא אל תשיב להודעה זו.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  try {
    await sendEmail({
      to:      customerEmail,
      subject: `לינק לתשלום חשבונית #${invoiceNumber}`,
      html,
    });
    logger.info('sendPaymentLinkEmail: sent', { linkId: id, to: customerEmail });
  } catch (err) {
    logger.error('sendPaymentLinkEmail: failed', {
      linkId: id,
      err:    err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}
